version: '2'
services:
  kanboard:
    container_name: 'kanext-kanboard'
    build: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.data:/var/www/app/data
      - ./.plugins:/var/www/app/plugins
      - ../src:/var/www/app/plugins/Kanext
    environment:
      - KANBOARD_PLUGIN_INSTALLER="true"
